---
- name: Install Drush
  shell:
    curl http://files.drush.org/drush.phar -L -o drush.phar && chmod +x drush.phar && mv drush.phar /usr/local/bin/drush
    creates=/usr/local/bin/drush

- name: Install Drupal Console
  shell:
    curl http://drupalconsole.com/installer -L -o drupal.phar && chmod +x drupal.phar && mv drupal.phar /usr/local/bin/drupal
    creates=/usr/local/bin/drupal
