---
- name: Install MariaDB
  hosts: db-server
  remote_user: myuser
  become: yes

  vars:
    mysql_root_password: 'my_secure_pass'
    mysql_bind_address: private_mysql_server_ip
    query_cache_limit: 4M
    query_cache_size: 256M
    key_buffer_size: 128M
    long_query_time: 2
    myisam_sort_buffer_size: 128M
    innodb_buffer_pool_size: 24G
    innodb_log_file_size: 512M

    dbs:
      mydb:
        dbuser: mydb
        dbpass: mydb
        dbhost: private_drupal_server_ip

  roles:
    - { role: common, tags: [common] }
    - { role: mysql , tags: [mysql] }

- name: Install Drupal and Drush with Nginx, and PHP-FPM
  hosts: drupal-server
  user: root
  remote_user: myuser
  become: yes

  vars:
    opcache_memory_consumption: 256

    fastcgi_buffers: 64

    pm_max_children: 200
    pm_start_servers: 100
    pm_min_spare_servers: 100
    pm_max_spare_servers: 200
    pm_max_requests: 10000

    sites:
      www.radec.com.mx:
        git: "http://git.drupal.org/project/drupal.git"
        version: master
        default: yes

  roles:
    - { role: common, tags: [common] }
    - { role: mailer, tags: [mailer] }
    - { role: nginx, tags: [nginx] }
    - { role: php-fpm, tags: [php-fpm] }
    - { role: console, tags: [console] }
    - { role: drupal, tags: [drupal] }
    - { role: syslog, tags: [syslog] }
